[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

## Domain redirect for http
[[redirects]]
  from = "http://elden-hexo-starter.netlify.app/*"
  to = "https://www.elden-williams.com/:splat"
  status = 301
  force = true

## Domain redirect for https
[[redirects]]
  from = "https://elden-hexo-starter.netlify.app/*"
  to = "https://www.elden-williams.com/:splat"
  status = 301
  force = true